### ISSUE TITLE
Interface proposal

### ISSUE THREAD

**Issue by sungwoncho** [dnote-io/cli#10]
## dnote books

Lists all books

## dnote use

Change the current book

## dnote notes

Lists all notes in the current book

**flags**

* `-b` - optionally specify the book name

## dnote ls (alternative to `dnote notes`)

Lists all notes in the current book

**argument**

* [book name] - optionally specify the book name

e.g.

    dnote notes -b “html”

## dnote new

Write a new note in the current book

**flags**

* `-b` - optionally specify the book name

**question**

Having added `-b` flag, should we also have a flag for the actual note content?

i.e.

    dnote new -b html "some note”

vs

    dnote new -b html -m "some note”

Does the first example seem inconsistent?

## dnote login

get API key from user input and save to `.dnoterc`

## dnote sync

sync with the server

**Comment by michielboekhoff** [comment]
And what about shortcuts for commands? Like `n` rather than `new` and `b` rather than `books`?

**Comment by YiiKuoChong** [comment]
@sungwoncho I don't think dnote ls is necessary. If it is for the sake of speed when typing why not change dnote notes to dnote ls instead?

**Comment by sungwoncho** [comment]
@YiiKuoChong we can have both `ls` and `notes` and make one an alias for another. In the future we can deprecate the alias if needed.

**Comment by sungwoncho** [comment]
As an experiment, `dnote ls` is now an alias for `dnote notes`. #36
