### ISSUE TITLE
Write tests to ensure feature-correctness.

### ISSUE THREAD

**Issue by michielboekhoff** [dnote-io/cli#12]
As the project grows - which I certainly hope - and more features will be added, it will become more necessary to verify that new things don't break old things. As such, I think it would be very useful to at least implement unit tests of some sort.

**Comment by michielboekhoff** [comment]
@sungwoncho, any thoughts?

**Comment by sungwoncho** [comment]
It is a good idea. We don't need to aim for a high coverage but it would be useful to have unit tests for some important functions.

**Comment by michielboekhoff** [comment]
Once #39 is merged, I'll look towards setting up some basic tests.

**Comment by sungwoncho** [comment]
Done in [v0.2.0](https://github.com/dnote-io/cli/releases/tag/v0.2.0). Thanks.
