### ISSUE TITLE
Migrate to JSON

### ISSUE THREAD

**Issue by sungwoncho** [dnote-io/cli#13]
Migrate YAML to JSON

**pros:**

- Able to store metadata other than note itself (createdAt, id, etc.)
  - allows us to implement reminder (e.g. remind what we learned 3 days ago, 7 days ago, etc.) Something like `dnote remind`, `dnote random`
  - allows us to move notes to different books: `dnote mv [noteId] [bookName]`

**cons:**

- Hard to read `~/.dnote` manually (have to use `dnote notes` or web interface for clean, easily readable output)

**assumption**

* Users will read the contents of `~/.dnote` not manually using `cat`, but by using `dnote notes` or web interface.

Feedback welcomed. How do you feel about this @michielboekhoff?

**Comment by michielboekhoff** [comment]
@sungwoncho I'd be for JSON. 

> Hard to read ~/.dnote manually (have to use dnote notes or web interface for clean, easily readable output)

I don't actually agree. JSON is a human-readable format.

I think another pro of using JSON would be to make it easier to have a web-based variant as well. Considering JSON is somewhat of an API standard these days, using JSON would be easier to integrate with the back-end.

**Comment by michielboekhoff** [comment]
I see you've merged #14, nice one! Maybe then you should close this issue, and add the new commands to #10 so we keep that discussion & those commands in one comprehensive list?

**Comment by sungwoncho** [comment]
Thanks for sharing your opinion. Closing this for now, but if anyone has other opinions please feel free to comment.
