### ISSUE TITLE
Show books even if they have no notes

### ISSUE THREAD

**Issue by zacoid55** [dnote-io/cli#2]
At the moment when you create a book, you can't view them by using `dnote books` and they only appear after adding a note.

It would be awesome of you can see books in the list without notes in them, is this possible?

**Comment by michielboekhoff** [comment]
@sungwoncho The way I see it, there's two approaches to this: 

1. we can store the books in a separate file from the notes, and have the notes "belong" to them, by including a book UID;
2. we can used a nested JSON structure is ~/.dnote, where `notes` is a child of books.

I've got some code written for this - what approach would you prefer?

**Comment by zacoid55** [comment]
Seeing as though you've switched over to JSON anyway, that would probably be the best, right?

**Comment by michielboekhoff** [comment]
@zacoid55 Depends on multiple things - there can be something said for a flat structure, depending on the back-end and future extensibility. I personally think nesting should be the way to go, if we're strictly speaking about a RESTful JSON API on the back-end.

**Comment by zacoid55** [comment]
Sounds good to me 👍

**Comment by michielboekhoff** [comment]
I've just created a PR: #20 that solves this issue.
