### ISSUE TITLE
[interface] dnote new should optionally take book name as an argument

### ISSUE THREAD

**Issue by sungwoncho** [dnote-io/cli#21]
It is hard to keep checking which book you are in, or switch books to write notes in.

Therefore the following is useful:

    dnote new js "my lesson"

Compared to:

    dnote books
    dnote use js
    dnote new "my lesson"

Alternatively we could use a flag such that:

    dnote new -b js "my lesson"

but `dnote new js "my lesson"` is easier to type, and has less friction.

The book name argument is optional. If omitted, the lesson will be written in the current book.

**Comment by michielboekhoff** [comment]
I can get started on this next week, probably even tomorrow.
