### ISSUE TITLE
Add continuous integration by Travis.

### ISSUE THREAD

**Issue by michielboekhoff** [dnote-io/cli#24]
Because of my silly mistake earlier, it became evident how important CI is in ensuring the build is working. This would go well with #12 to test the software. I'm willing to create a PR for this.

**Comment by michielboekhoff** [comment]
I'll pick this up today.

**Comment by michielboekhoff** [comment]
Actually, I just found out that I cannot do this, as I am not a member of the dnote-io organisation. @sungwoncho, would you mind setting it up?

**Comment by sungwoncho** [comment]
Sorry for the delay. I have added you.

**Comment by sungwoncho** [comment]
Done in [v0.2.0](https://github.com/dnote-io/cli/releases/tag/v0.2.0).
