### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by YiiKuoChong** [dnote-io/cli#25]
As the dnote is designed to quickly write down what we learn with minimal context switching while coding, I think it would be a good idea to integrate a "help" command. This way users would need not to switch between GUI and CLI for reference, thus saving time.

**Comment by YiiKuoChong** [comment]
Implemented a help function.

**Comment by sungwoncho** [comment]
Most commands are not self documenting and prints out usage examples. Please reopen if you think it can be improved further.
