### ISSUE TITLE
Installer

### ISSUE THREAD

**Issue by YiiKuoChong** [dnote-io/cli#27]
As the user base grow, I think it would become a need for installers to exist that support major platforms such as Windows, Linux and Mac OS. I hope someone could take up the challenge and create this.

**Comment by michielboekhoff** [comment]
We'll have to look into how to automate distribution for each platform. I think for the time being, it would make sense to simply set up a PPA, to see how this could go. Any thoughts, @sungwoncho?

**Comment by michielboekhoff** [comment]
Just an FYI: I can distribute a package for Fedora & Debian.

**Comment by sungwoncho** [comment]
I think installer is unnecessary for the time being.

We have a simple solution that works for all platforms: Github release, [install script](https://github.com/dnote-io/cli/blob/master/install.sh). Also we have auto-update. Let us close this for now if there is not significant added benefit.

**Comment by sungwoncho** [comment]
Closing this for now due to inactivity.
