### ISSUE TITLE
Sync between different machines?

### ISSUE THREAD

**Issue by derekhh** [dnote-io/cli#33]
Initially I thought `dnote sync` would sync my notes with the server and then whenever I use `dnote` on a new machine I can just do `dnote login` and then `dnote sync` to download my notes. Seems that's not the case.

Is this something you are planning to add?

**Comment by sungwoncho** [comment]
Yes, the plan is to make `/sync` endpoint reply with notes that are present in the server but not in the payload from the user. See [this comment](https://github.com/dnote-io/api/blob/master/handlers.go#L193-L196).

Then the client will use the payload from the server to insert missing notes to `.dnote`.

How important do you think this feature is? And any alternative solutions you can think of?

**Comment by derekhh** [comment]
Thanks! It's great to know this is a planned feature.

I am highly biased towards my own viewpoint because I use multiple machines fairly often and whether I can have a synchronized version of notebooks basically is a killer feature for me. I like Dnote because I've been using Git to take long technical notes for a while but I can't figure out a good minimalistic way to take short notes like this.

Technically I think the current solution would probably be good enough given most users won't have that many notes so the size of the payload should be fairly small in that it won't affect the performance of `dnote sync` that much.

One minor concern is related to how traditional version control systems handle merge conflicts and whether this would affect your design while syncing the notes. But since these notes are so short maybe it doesn't matter?

**Comment by sungwoncho** [comment]
@derekhh I have implemented this in v0.2.0 along with other improvements. If you are curious, my solution to conflict resolution was:

Every time a note or a book is mutated, an action is recorded locally. `dnote sync` will push those actions to the server. Server will process those actions, mark previous actions as obsolete where needed, and respond with actions that have not been synced with the client yet. And the cli will process those actions to bring the local copy up-to-date with the server copy.

I shipped this as a [premium feature](http://dnote.io/cloud) but you can use it for free if you are still using dnote. Let me know.
