### ISSUE TITLE
Broken colors

### ISSUE THREAD

**Issue by nblackburn** [dnote-io/cli#59]
CLI colors are broken in windows, instead i see this...

```
  ?[37m•?[0m git ?[33m(1)?[0m
  ?[37m•?[0m linux ?[33m(1)?[0m
  ?[37m•?[0m test ?[33m(1)?[0m
```

**Comment by iantervela** [comment]
Found this as I'm seeing the same, although it is simple enough to open in Cygwin:

https://github.com/Microsoft/WSL/issues/1173

**Comment by sungwoncho** [comment]
Does it happen on all machines running Windows? Could you specify an environment in which this issue happens?

**Comment by FearNotDaniel** [comment]
Hi @sungwoncho I'm not the OP of this issue but I've just found the same problem. I've tested in both cmd and powershell, under both Win7 and Win10, all have the same issue.
![dnote-ps-win10](https://user-images.githubusercontent.com/14836055/36145937-d4b2e32c-10aa-11e8-8595-eed8865d8a7b.png)

**Comment by iantervela** [comment]
I'm seeing this behavior on Windows 10 cmd and powershell:

```
PS C:\Users\Ian> [System.Environment]::OSVersion.Version

Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      16299  0

PS C:\Users\Ian> dnote ls
  [37m•[0m git [33m(3)[0m
  [37m•[0m dnote [33m(2)[0m
  [37m•[0m something [33m(1)[0m
```

**Comment by nblackburn** [comment]
@sungwoncho i can confirm it happens in cmd and powershell and have tested it on two machines.

**Comment by sungwoncho** [comment]
Fixed by https://github.com/dnote-io/cli/pull/73 thanks @FearNotDaniel.

Release in https://github.com/dnote-io/cli/releases/tag/v0.2.1. You can run `dnote upgrade` to upgrade.

**Comment by iantervela** [comment]
Confirmed working for me on Windows 10 in PS and cmd.

**Comment by nblackburn** [comment]
Looks good to me
