### ISSUE TITLE
utils/utils.go:27:19: multiple-value uuid.NewV4() in single-value context

### ISSUE THREAD

**Issue by Vaelatern** [dnote-io/cli#65]
Also noted in `migrate/migrations.go:51:25`

Seems related to https://github.com/kataras/iris/issues/861
https://github.com/satori/go.uuid/issues/66

As the recommended way to continue the old behaviour (as mentioned in https://github.com/satori/go.uuid/commit/0ef6afb2f6cdd6cdaeee3885a95099c63f18fc8c) I am going to open a PR with the following patch.

```
--- utils/utils.go.bck  2018-02-13 03:06:34.295215926 -0500
+++ utils/utils.go      2018-02-13 03:06:52.708205990 -0500
@@ -24,7 +24,7 @@

 // GenerateUID returns a uid
 func GenerateUID() string {
-       return uuid.NewV4().String()
+       return uuid.Must(uuid.NewV4()).String()
 }

 func GetInput() (string, error) {
--- migrate/migrations.go.bck   2018-02-13 03:10:28.827089361 -0500
+++ migrate/migrations.go       2018-02-13 03:10:51.090077347 -0500
@@ -48,7 +48,7 @@
                notes := []migrateToV2PostNote{}
                for _, note := range book {
                        newNote := migrateToV2PostNote{
-                               UUID:     uuid.NewV4().String(),
+                               UUID:     uuid.Must(uuid.NewV4()).String(),
                                Content:  note.Content,
                                AddedOn:  note.AddedOn,
                                EditedOn: 0,
```

**Comment by sungwoncho** [comment]
Seems to happen in the `master` branch of upstream but our dependency version is frozen to a release version.

The issue might be that `dep ensure` was not run. Maybe we can make a contribution guide for others wanting to build the project to prevent confusion.
