### ISSUE TITLE
Delete note fails in Windows cmd/powershell

### ISSUE THREAD

**Issue by FearNotDaniel** [dnote-io/cli#67]
Running delete command in Windows cmd or powershell results in 'aborted by user' message after responding to the confirmation prompt with lowercase y and pressing enter. Tested on both Win7 and Win10. Command does behave correctly under msysgit bash emulator on Win7.

![image](https://user-images.githubusercontent.com/14836055/36146606-1f7c371c-10ad-11e8-8f7b-752bdef960a5.png)

![image](https://user-images.githubusercontent.com/14836055/36146680-57846a9e-10ad-11e8-9556-af6eaa482283.png)

**Comment by sungwoncho** [comment]
I think I have a fix here: https://github.com/dnote-io/cli/releases/tag/v0.2.1-beta

I will confirm and release the patch once I test on Windows. Currently only have access to a mac.

**Comment by FearNotDaniel** [comment]
Great, thanks. I tested in msysgit on Win7 and PS on Win10 and both seem to work:

![image](https://user-images.githubusercontent.com/14836055/36149034-14ab2af6-10b6-11e8-84a7-2e271473c9a3.png)

![dnote-delete-test-win10-ps](https://user-images.githubusercontent.com/14836055/36149026-07b02bd0-10b6-11e8-8206-f6d6a12ed46c.png)

Obviously the PS output is still affected by #59 but current issue seems to be resolved.

**Comment by FearNotDaniel** [comment]
@sungwoncho if it helps, these free VMs are extremely useful for testing apps against different Windows versions; I run several in VirtualBox even when I'm using native Windows:

https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

**Comment by sungwoncho** [comment]
Fixed in https://github.com/dnote-io/cli/releases/tag/v0.2.1
