### ISSUE TITLE
dnote not recognized as an internal or external command

### ISSUE THREAD

**Issue by grmnn** [dnote-io/cli#70]
Hi! At first I am relatively new to using the CLI. 

I'm using windows 10. 

I change the directory to the folder where the .exe is and type the name of the .exe file and hit enter

My problem is, i can't use any commands, even though it looks like I should be able to.

![cli-error](https://user-images.githubusercontent.com/30831286/36150582-77441c14-10c4-11e8-9614-a90e1a6b6511.png)

The error says:  "dnote" is not recognized as an internal or external command.." 

I tried it in different terminals (Git, Powershell, CMD) also running it as administrator but nothing seems to work.

**Comment by FearNotDaniel** [comment]
Guten Tag, @grmnn - I came across this too. It's not an issue with the app, but more a consequence that the binary doesn't come with an installer. You need to rename the download to dnote.exe and then do **one** of the following:

- move the .exe into a directory which is already included in your system path; or
- add the .exe's directory to your system path

You can find your current system path by typing `echo %path%` in cmd.exe, or `$env:path` in PowerShell.

**Comment by grmnn** [comment]
It works now, thanks!
