### ISSUE TITLE
Can I build my own cloud server?

### ISSUE THREAD

**Issue by ginhton** [dnote-io/cli#71]
I wonder if there is some method for me to build my own cloud server. And I can store my data in it and share the server with my classmates. 
Thank you all. This is a wonderful project!

**Comment by sungwoncho** [comment]
The server works like this https://github.com/dnote-io/cli/issues/48#issuecomment-355732636. But I feel that for you to implement it will be impractical because there are rough edges and the server might break when CLI changes.

If you are a student, just drop me an email on my github profile.

**Comment by ginhton** [comment]
Thank you for your advice! This is a very interesting work. I want to learn more about it by myself.
And I found a repo which has the same idea of implement a server. [DnoteServer](https://github.com/vms20591/DnoteServer)

**Comment by sungwoncho** [comment]
@ginhton now Dnote server is [open source](https://dnote.io/blog/open-sourcing-dnote) and there is an [official self hosting guide](https://github.com/dnote/dnote/blob/master/SELF_HOSTING.md).

As for sharing with data with your classmates, Dnote is now end-to-end encrypted and public note support was dropped to focus more on privacy. There is [a discussion](https://forum.dnote.io/t/should-dnote-support-public-notes/28) about it on forum.

Hope this helps!
